config/routes.rb
Rails.application.routes.draw do
  resources :newsletterusers
  resources :columnists
  resources :companies
  get 'sessions/new'
  resources :sessions
  resources :users
  resources :subcategories
  resources :categories
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get "columnista" => "home#columnista", :as => "columnista" 
  root :to => 'home#index'
  get "pach" => "home#pach", :as => "pach" 
  get "editsubcategoria" => "home#editsubcategoria", :as => "editsubcategoria"
  get "editcategoria" => "home#editcategoria", :as => "editcategoria"
  get "eliminarsubcategoria" => "home#eliminarsubcategoria", :as => "eliminarsubcategoria"
  get "eliminarcategoria" => "home#eliminarcategoria", :as => "eliminarcategoria"
  get "terms" => "home#terms", :as => "terms"  
  get "privacy" => "home#privacy", :as => "privacy"
  get "post_detail" => "home#post_detail", :as => "post_detail"
  get "eliminarcolumnist" => "home#eliminarcolumnist", :as => "eliminarcolumnist"
  get "editcolumnist" => "home#editcolumnist", :as => "editcolumnist"
  get "eliminarcompany" => "home#eliminarcompany", :as => "eliminarcompany"
  get "eliminarpost" => "home#eliminarpost", :as => "eliminarpost"
  get "editpost" => "home#editpost", :as => "editpost"
  get "editcompany" => "home#editcompany", :as => "editcompany"
  get "delete_all_posts" => "home#delete_all_posts", :as => "delete_all_posts"
  get "admin" => "home#admin", :as => "admin"
  get "comunity" => "home#comunity", :as => "comunity"
  get "about" => "home#about", :as => "about"
  get "blog" => "home#blog", :as => "blog"
  get "contacto" => "home#contacto", :as => "contacto"
  get "services" => "home#services", :as => "services"
  get "logoutadmin" => "sessions#destroy", :as => "logoutadmin"
  get "loginadmin" => "sessions#create", :as => "loginadmin"
  get "thankyou_contact" => "home#thankyou_contact", :as => "thankyou_contact"
  get "fillall" => "home#fillall", :as => "fillall"
  post "sendContactRequest" => "home#sendContactRequest", :as => "sendContactRequest"
  post "sendNewsletter" => "home#sendNewsletter", :as => "sendNewsletter"
  get "thankyou_newsletter" => "home#thankyou_newsletter", :as => "thankyou_newsletter"
  get "search" => "home#search", :as => "search"
  get "service_propiedad_intelectual" => "home#service_propiedad_intelectual", :as => "service_propiedad_intelectual"
  get "service_liderazgo" => "home#service_liderazgo", :as => "service_liderazgo"
  get "service_coaching" => "home#service_coaching", :as => "service_coaching"
  get "columnistas" => "home#columnistas", :as => "columnistas"
  get "columnista_detalle" => "home#columnista_detalle", :as => "columnista_detalle"
  get "/empresa/:id", :controller => "home", :action => "empresa"
  get "/publicacion/:id", :controller => "home", :action => "publicacion"
  get "/columnista/:id", :controller => "home", :action => "columnista"
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
	self.primary_key = "id"


	before_create :check_max_value

def check_max_value

	if Subcategory.last != nil

	    self.id = Subcategory.last.id + 1
	    self.subcat_id = Subcategory.last.id + 1


	else

		self.id = 1
    	self.subcat_id = 1

	end


end



end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all.reverse
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to subcategories_url, notice: 'Subcategoria cargada correctamente' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to subcategories_url, notice: 'Subcategoria actualizada correctamente' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: 'Subcategoria eliminada correctamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :subcat_id, :id)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
  <%= form_with(model: @subcategory, local: true) do |form| %>

       <div class="box-body">



               <div class="form-group">
                  <label for="exampleInputEmail1">Nombre Subcategoría *</label>
                 <input class="form-control"  name="subcategory[name]" value="<%= @subcategory.name %>" placeholder="<%= @subcategory.name %>" size="30" type="text" required>
                </div>
           
          




    <div class="form-group">
        <button type="submit" name="submit" class="btn btn-primary">Cargar Subcategoría</button>
          
    </div>



</div>
<% end %>

app/views/subcategories/edit.html.erb
    <% if session[:user_id] %>
     <%= render 'layouts/header' %>
   <div class="content-wrapper">
<section class="content">
    
<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Editar Subcategoría</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           
	<%= render 'form', staff: @subcategory %>

 	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>

    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css">





          </div>
    </section>

        </div>
<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>

app/views/subcategories/index.html.erb
 <% if session[:user_id] %>
  <% @current_user ||= User.find(session[:user_id]) if session[:user_id] %>

   <%= render 'layouts/header' %>
   <div class="content-wrapper">
    <!-- Content Header (Page header) -->


    <!-- Main content -->
    <section class="content">
<div class="row">
  <div class="col-md-12">
      <div class="boxed">
                <!-- Title Bart Start -->

          


<h2>Listado de Subcategorías <a href="/subcategories/new" style="font-size: 16px;">Cargar Subcategoría</a></h2>

    <div class="inner no-radius">


  <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                  <thead>
                    <tr>
                       <th>ID</th>
                          <th>Nombre</th>
 
                 

                    
                            <th colspan="3"></th>
                             <th colspan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
  
 <% @subcategories.each do |cat| %>
                    <tr>
                <td><%= cat.subcat_id %></td>                                
             <td><%= cat.name %></td>

        <td><a href="/editsubcategoria?subcat_id=<%= cat.subcat_id %>">Editar</a></td>
        <td><a href="/eliminarsubcategoria?subcat_id=<%= cat.subcat_id %>">Eliminar</a></td>
                    </tr>

                  
 <% end %>



                  </tbody>
                </table>



        </div>


      </div>
</div>
</div>





</section>
</div>

<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>

app/views/subcategories/new.html.erb
   <% if session[:user_id] %>
     <%= render 'layouts/header' %>
   <div class="content-wrapper">
<section class="content">
    
<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Cargar Subcategoría</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           
	<%= render 'form', staff: @subcategory %>

 	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>

    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css">





          </div>
    </section>

        </div>
<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>

app/views/subcategories/show.html.erb
 <% if session[:user_id] %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subcategory.name %>
</p>

<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>
<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>