config/routes.rb
Rails.application.routes.draw do
  resources :newsletterusers
  resources :columnists
  resources :companies
  get 'sessions/new'
  resources :sessions
  resources :users
  resources :subcategories
  resources :categories
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get "columnista" => "home#columnista", :as => "columnista" 
  root :to => 'home#index'
  get "pach" => "home#pach", :as => "pach" 
  get "editsubcategoria" => "home#editsubcategoria", :as => "editsubcategoria"
  get "editcategoria" => "home#editcategoria", :as => "editcategoria"
  get "eliminarsubcategoria" => "home#eliminarsubcategoria", :as => "eliminarsubcategoria"
  get "eliminarcategoria" => "home#eliminarcategoria", :as => "eliminarcategoria"
  get "terms" => "home#terms", :as => "terms"  
  get "privacy" => "home#privacy", :as => "privacy"
  get "post_detail" => "home#post_detail", :as => "post_detail"
  get "eliminarcolumnist" => "home#eliminarcolumnist", :as => "eliminarcolumnist"
  get "editcolumnist" => "home#editcolumnist", :as => "editcolumnist"
  get "eliminarcompany" => "home#eliminarcompany", :as => "eliminarcompany"
  get "eliminarpost" => "home#eliminarpost", :as => "eliminarpost"
  get "editpost" => "home#editpost", :as => "editpost"
  get "editcompany" => "home#editcompany", :as => "editcompany"
  get "delete_all_posts" => "home#delete_all_posts", :as => "delete_all_posts"
  get "admin" => "home#admin", :as => "admin"
  get "comunity" => "home#comunity", :as => "comunity"
  get "about" => "home#about", :as => "about"
  get "blog" => "home#blog", :as => "blog"
  get "contacto" => "home#contacto", :as => "contacto"
  get "services" => "home#services", :as => "services"
  get "logoutadmin" => "sessions#destroy", :as => "logoutadmin"
  get "loginadmin" => "sessions#create", :as => "loginadmin"
  get "thankyou_contact" => "home#thankyou_contact", :as => "thankyou_contact"
  get "fillall" => "home#fillall", :as => "fillall"
  post "sendContactRequest" => "home#sendContactRequest", :as => "sendContactRequest"
  post "sendNewsletter" => "home#sendNewsletter", :as => "sendNewsletter"
  get "thankyou_newsletter" => "home#thankyou_newsletter", :as => "thankyou_newsletter"
  get "search" => "home#search", :as => "search"
  get "service_propiedad_intelectual" => "home#service_propiedad_intelectual", :as => "service_propiedad_intelectual"
  get "service_liderazgo" => "home#service_liderazgo", :as => "service_liderazgo"
  get "service_coaching" => "home#service_coaching", :as => "service_coaching"
  get "columnistas" => "home#columnistas", :as => "columnistas"
  get "columnista_detalle" => "home#columnista_detalle", :as => "columnista_detalle"
  get "/empresa/:id", :controller => "home", :action => "empresa"
  get "/publicacion/:id", :controller => "home", :action => "publicacion"
  get "/columnista/:id", :controller => "home", :action => "columnista"
end

app/models/columnist.rb
class Columnist < ApplicationRecord



has_attached_file :picture
validates_attachment_presence :picture
validates_attachment_size :picture, :less_than => 100.megabytes
validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png', 'image/jpg']
before_create :check_max_value


validates_uniqueness_of :full_name

  has_many :posts
  self.primary_key = "id"

  def check_max_value
  	if Columnist.last != nil

  	    self.id = Columnist.last.id + 1
        self.colm_id = Columnist.last.id + 1

	else
		self.id = 1
        self.colm_id = 1

	end

  end


end

app/controllers/columnists_controller.rb
class ColumnistsController < ApplicationController
  before_action :set_columnist, only: [:show, :edit, :update, :destroy]

  # GET /columnists
  # GET /columnists.json
  def index
    @columnists = Columnist.all
  end

  # GET /columnists/1
  # GET /columnists/1.json
  def show
     session[:user_id] = nil
  end

  # GET /columnists/new
  def new
    @columnist = Columnist.new
  end

  # GET /columnists/1/edit
  def edit
  end

  # POST /columnists
  # POST /columnists.json
  def create
    @columnist = Columnist.new(columnist_params)

    respond_to do |format|
      if @columnist.save
        format.html { redirect_to columnists_url, notice: 'Columnist was successfully created.' }
        format.json { render :show, status: :created, location: @columnist }
      else
        format.html { render :new }
        format.json { render json: @columnist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /columnists/1
  # PATCH/PUT /columnists/1.json
  def update
    respond_to do |format|
      if @columnist.update(columnist_params)
        format.html { redirect_to columnists_url, notice: 'Columnist was successfully updated.' }
        format.json { render :show, status: :ok, location: @columnist }
      else
        format.html { render :edit }
        format.json { render json: @columnist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /columnists/1
  # DELETE /columnists/1.json
  def destroy
    @columnist.destroy
    respond_to do |format|
      format.html { redirect_to columnists_url, notice: 'Columnist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_columnist
      @columnist = Columnist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def columnist_params
      params.require(:columnist).permit(:full_name, :socials, :semblanza, :picture, :facebook, :twitter, :linkedin, :instagram, :id, :colm_id)
    end
end

app/views/columnists/_form.html.erb
  <%= form_with(model: @columnist, local: true) do |form| %>

       <div class="box-body">

<% if @columnist.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-ban"></i> Debes llenar los campos! faltaron:</h4>
                
   
      <% @columnist.errors.full_messages.each do |message| %>


               <p><%= message %></p>

      <% end %>
      </div>
    </div>
  <% end %>

  

               <div class="form-group">
                  <label for="exampleInputEmail1">Nombre Completo *</label>
                 <input class="form-control"  name="columnist[full_name]" value="<%= @columnist.full_name %>" placeholder="Nombre Completo *" size="30" type="text" required>
                </div>
           
        
                    <div class="form-group">
                  <label for="exampleInputEmail1">Facebook</label>
                 <input class="form-control"  name="columnist[facebook]" value="<%= @columnist.facebook %>" placeholder="Facebook Empresa" size="30" type="text">
                </div>
           



                    <div class="form-group">
                  <label for="exampleInputEmail1">Twitter</label>
                 <input class="form-control"  name="columnist[twitter]" value="<%= @columnist.twitter %>" placeholder="Twitter Empresa" size="30" type="text" >
                </div>
           



                    <div class="form-group">
                  <label for="exampleInputEmail1">Instagram</label>
                 <input class="form-control"  name="columnist[instagram]" value="<%= @columnist.instagram %>" placeholder="Instagram Empresa" size="30" type="text">
                </div>
           
                   <div class="form-group">
                  <label for="exampleInputEmail1">Linkedin</label>
                 <input class="form-control"  name="columnist[linkedin]" value="<%= @columnist.linkedin %>" placeholder="Linkedin Empresa" size="30" type="text">
                </div>

                    <div class="form-group">
                  <label for="exampleInputEmail1">Semblanza * Palabras: <span id="display_count">0</span> </label>
                  <textarea id="word_count" rows="4" cols="50" class="form-control"  name="columnist[semblanza]" value="<%= @columnist.semblanza %>">
                    <%= @columnist.semblanza %>
                    </textarea>
                <!--  <input class="form-control"  name="columnist[semblanza]" value="<%= @columnist.semblanza %>" placeholder="Semblanza *" size="30" type="text" required> -->
                </div>
           
         
         <div class="form-group">
                  <label for="exampleInputEmail1">Foto de Columnista *</label>
                 <%= form.file_field :picture %>

                </div>


      


    <div class="form-group">
        <button type="submit" name="submit" class="btn btn-primary">Cargar Columnista</button>
          
    </div>



</div>

<script type="text/javascript">

  $( window ).on( "load", function() { 

      $("#word_count").on('keyup', function() {
        var words = this.value.match(/\S+/g).length;
     $('#display_count').text(words);
    });

    var words = document.getElementById('word_count').value.match(/\S+/g).length;
     $('#display_count').text(words);

   });


  $(document).ready(function() {
        $("#word_count").on('keyup', function() {
        var words = this.value.match(/\S+/g).length;
     $('#display_count').text(words);
    });

    var words = document.getElementById('word_count').value.match(/\S+/g).length;
     $('#display_count').text(words);

 }); 
</script>

<% end %>

app/views/columnists/edit.html.erb
     <% if session[:user_id] %>
     <%= render 'layouts/header' %>
   <div class="content-wrapper">
<section class="content">
    
<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Editar Columnista</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           
	<%= render 'form', staff: @columnist %>


          </div>
    </section>

        </div>
<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>

app/views/columnists/index.html.erb
 <% if session[:user_id] %>

  <% @current_user ||= User.find(session[:user_id]) if session[:user_id] %>

   <%= render 'layouts/header' %>
   <div class="content-wrapper">
    <!-- Content Header (Page header) -->


    <!-- Main content -->
    <section class="content">
<div class="row">
  <div class="col-md-12">
      <div class="boxed">
                <!-- Title Bart Start -->

          


<h2>Listado de Columnistas <a href="/columnists/new" style="font-size: 16px;">Cargar Columnista</a></h2>

    <div class="inner no-radius">


  <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                  <thead>
                    <tr>
                            <th>ID</th>
                            <th>Foto</th>
                            <th>Nombre</th>
                            <th>Facebook</th>
                            <th>Instagram</th>
                            <th>Twitter</th>
                            <th>Linkedin</th>
                            <th>Semblanza</th>
                  
                          
                             <th colspan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
  
  <% @columnists.each do |columnist| %>
      <tr>
        <td><%= columnist.colm_id %></td>
  <td><img src="<%= columnist.picture.url %>" style="width:70px;height:70px;border-radius: 50%;"></td>
        <td><%= columnist.full_name %></td>
          <td><%= columnist.facebook %></td>
          <td><%= columnist.instagram %></td>
          <td><%= columnist.twitter %></td>
          <td><%= columnist.linkedin %></td>
              <td><%= columnist.semblanza %></td>


 
<td><a href="/editcolumnist?columnist_id=<%= columnist.colm_id %>">Editar</a></td>
        <td><a href="/eliminarcolumnist?columnist_id=<%= columnist.colm_id %>">Eliminar</a></td>
      </tr>
    <% end %>



                  </tbody>
                </table>



        </div>


      </div>
</div>
</div>





</section>
</div>
<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>

app/views/columnists/new.html.erb
     <% if session[:user_id] %>
     <%= render 'layouts/header' %>
   <div class="content-wrapper">
<section class="content">
    
<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Cargar Columnista</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           
	<%= render 'form', staff: @columnist %>



          </div>
    </section>

        </div>
<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>

app/views/columnists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @columnist.full_name %>
</p>

<p>
  <strong>Socials:</strong>
  <%= @columnist.socials %>
</p>

<p>
  <strong>Semblanza:</strong>
  <%= @columnist.semblanza %>
</p>

<%= link_to 'Edit', edit_columnist_path(@columnist) %> |
<%= link_to 'Back', columnists_path %>