config/routes.rb
Rails.application.routes.draw do
  resources :newsletterusers
  resources :columnists
  resources :companies
  get 'sessions/new'
  resources :sessions
  resources :users
  resources :subcategories
  resources :categories
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get "columnista" => "home#columnista", :as => "columnista" 
  root :to => 'home#index'
  get "pach" => "home#pach", :as => "pach" 
  get "editsubcategoria" => "home#editsubcategoria", :as => "editsubcategoria"
  get "editcategoria" => "home#editcategoria", :as => "editcategoria"
  get "eliminarsubcategoria" => "home#eliminarsubcategoria", :as => "eliminarsubcategoria"
  get "eliminarcategoria" => "home#eliminarcategoria", :as => "eliminarcategoria"
  get "terms" => "home#terms", :as => "terms"  
  get "privacy" => "home#privacy", :as => "privacy"
  get "post_detail" => "home#post_detail", :as => "post_detail"
  get "eliminarcolumnist" => "home#eliminarcolumnist", :as => "eliminarcolumnist"
  get "editcolumnist" => "home#editcolumnist", :as => "editcolumnist"
  get "eliminarcompany" => "home#eliminarcompany", :as => "eliminarcompany"
  get "eliminarpost" => "home#eliminarpost", :as => "eliminarpost"
  get "editpost" => "home#editpost", :as => "editpost"
  get "editcompany" => "home#editcompany", :as => "editcompany"
  get "delete_all_posts" => "home#delete_all_posts", :as => "delete_all_posts"
  get "admin" => "home#admin", :as => "admin"
  get "comunity" => "home#comunity", :as => "comunity"
  get "about" => "home#about", :as => "about"
  get "blog" => "home#blog", :as => "blog"
  get "contacto" => "home#contacto", :as => "contacto"
  get "services" => "home#services", :as => "services"
  get "logoutadmin" => "sessions#destroy", :as => "logoutadmin"
  get "loginadmin" => "sessions#create", :as => "loginadmin"
  get "thankyou_contact" => "home#thankyou_contact", :as => "thankyou_contact"
  get "fillall" => "home#fillall", :as => "fillall"
  post "sendContactRequest" => "home#sendContactRequest", :as => "sendContactRequest"
  post "sendNewsletter" => "home#sendNewsletter", :as => "sendNewsletter"
  get "thankyou_newsletter" => "home#thankyou_newsletter", :as => "thankyou_newsletter"
  get "search" => "home#search", :as => "search"
  get "service_propiedad_intelectual" => "home#service_propiedad_intelectual", :as => "service_propiedad_intelectual"
  get "service_liderazgo" => "home#service_liderazgo", :as => "service_liderazgo"
  get "service_coaching" => "home#service_coaching", :as => "service_coaching"
  get "columnistas" => "home#columnistas", :as => "columnistas"
  get "columnista_detalle" => "home#columnista_detalle", :as => "columnista_detalle"
  get "/empresa/:id", :controller => "home", :action => "empresa"
  get "/publicacion/:id", :controller => "home", :action => "publicacion"
  get "/columnista/:id", :controller => "home", :action => "columnista"
end

app/models/category.rb
class Category < ApplicationRecord
	self.primary_key = "id"




	before_create :check_max_value

	def check_max_value

		if Category.last != nil
		  self.id = Category.last.id + 1
		  self.cat_id = Category.last.id + 1
		else
		  self.id = 1
		  self.cat_id = 1
		end

	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.reverse
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Categoria cargada correctamente' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Categoria actualizada correctamente' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categroria eliminada correctamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :cat_id, :id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
  <%= form_with(model: @category, local: true) do |form| %>

       <div class="box-body">



               <div class="form-group">
                  <label for="exampleInputEmail1">Nombre Categoría *</label>
                 <input class="form-control"  name="category[name]" value="<%= @category.name %>" placeholder="<%= @category.name %>" size="30" type="text" required>
                </div>
           
          




    <div class="form-group">
        <button type="submit" name="submit" class="btn btn-primary">Cargar Categoría</button>
          
    </div>



</div>
<% end %>

app/views/categories/edit.html.erb
 <% if session[:user_id] %>  
     <%= render 'layouts/header' %>
   <div class="content-wrapper">
<section class="content">
    
<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Editar Categoría</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           
	<%= render 'form', staff: @category %>

 	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>

    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css">





          </div>
    </section>

        </div>
<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>

app/views/categories/index.html.erb
 <% if session[:user_id] %>
  <% @current_user ||= User.find(session[:user_id]) if session[:user_id] %>

   <%= render 'layouts/header' %>
   <div class="content-wrapper">
    <!-- Content Header (Page header) -->


    <!-- Main content -->
    <section class="content">
<div class="row">
  <div class="col-md-12">
      <div class="boxed">
                <!-- Title Bart Start -->

          


<h2>Listado de Categorías <a href="/categories/new" style="font-size: 16px;">Cargar Categoría</a></h2>

    <div class="inner no-radius">


  <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                  <thead>
                    <tr>
                      <th>ID</th>
                          <th>Nombre</th>
 
                 

                    
                            <th colspan="3"></th>
                             <th colspan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
  
 <% @categories.each do |cat| %>
                    <tr>
                     <td><%= cat.cat_id %></td>                            
             <td><%= cat.name %></td>

        <td><a href="/editcategoria?cat_id=<%= cat.cat_id %>">Editar</a></td>
        <td><a href="/eliminarcategoria?cat_id=<%= cat.cat_id %>">Eliminar</a></td>



                    </tr>

                  
 <% end %>



                  </tbody>
                </table>



        </div>


      </div>
</div>
</div>





</section>
</div>

<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>

app/views/categories/new.html.erb
      <% if session[:user_id] %>
     <%= render 'layouts/header' %>
   <div class="content-wrapper">
<section class="content">
    
<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Cargar Categoría</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           
	<%= render 'form', staff: @category %>

 	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>

    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css">





          </div>
    </section>

        </div>
<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>

app/views/categories/show.html.erb
 <% if session[:user_id] %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<% else %><br><br><br><br>
<div align="center">

<h2>Cerraste tu sesión, vuelve a logearte</h2>
</div>
<br><br><br><br>
<% end %>